### ISSUE TITLE
Add vertico and selectrum faces

### ISSUE THREAD

**Issue by bdarcus** [mclear-tools/bespoke-themes#1]
Just thought I'd ask if you could include these, to match the ivy ones.

Modus has support for both:

https://github.com/protesilaos/modus-themes/blob/main/modus-themes.el

Also, more generally, though I'm unfamiliar with the details, see the `modus-themes-completions` defcustom, which seems like it might be useful:

https://github.com/protesilaos/modus-themes/blob/main/modus-themes.el#L2466

**Comment by mclearc** [comment]
Sure - though there are already faces for vertico and selectrum. If they aren’t working I’ll have to look into that. 

--
Colin McLear
Associate Professor
Department of Philosophy 
University of Nebraska–Lincoln
colinmclear.net

**Comment by bdarcus** [comment]
Oops; I thought I checked, but I guess not carefully enough!

I'll close this then.

**Comment by mclearc** [comment]
Glad that was easy - but I should probably alphabetize the faces so they are easier to find :)

--
Colin McLear
Associate Professor
Department of Philosophy 
University of Nebraska–Lincoln
colinmclear.net
