### ISSUE TITLE
My theme with your custom mode-line?

### ISSUE THREAD

**Issue by marcograhl** [mclear-tools/bespoke-themes#11]
Hey guys, is there a way to use the bespoke modeline with my config? I do like the style, its very minimal and cool -> good job on the theme.

**Comment by mclearc** [comment]
Thanks. I've been thinking about separating the mode line out from the theme itself, but I haven't really had time to do so. Also, there is already https://github.com/rougier/nano-modeline, which is very similar (and the inspiration really for this mode line). Perhaps you can try that out and see if you like it?

**Comment by marcograhl** [comment]
Alright I will give it a try. Thank you

**Comment by mclearc** [comment]
I'm going to close this issue, but i'll ping here if/when I separate out the modeline from the theme.

**Comment by mclearc** [comment]
In case this ends up being of help @marcograhl I've separated out the mode-line into its own repo: https://github.com/mclear-tools/bespoke-modeline
