### ISSUE TITLE
Highlighted selection  is barely visible in helm

### ISSUE THREAD

**Issue by proudot** [mclear-tools/bespoke-themes#12]
Hi there, thanks for the great theme. Whenever I use helm, the highlighted selection  is clear gray hence barely visible in 'light. Any idea how to change that ? The blue color that is used for the highlighted in smex would be fine. 

Also, how can we add a gray background to org-block equation ? Sorry if those are basic question, I still new to theming in emacs.

**Comment by proudot** [comment]
Update: I just toggled theme from light to dark and back to light and now the selected item is bold and black, much more visible! Any idea where the bug comes from  ?

**Comment by mclearc** [comment]
I don't use helm so I haven't tested this in awhile. The relevant lines to look at in the theme start here: https://github.com/mclear-tools/bespoke-themes/blob/f447c2ac79785621502ec934931cca05ab2c2851/bespoke-theme.el#L349

You might change `bespoke-subtle` to `bespoke-highlight` and see if that looks better. Also note that right now the colors are set to `foreground`, but if you prefer the background be highlighted you could set them to `background` instead.

**Comment by proudot** [comment]
Thanks for the fast reply. What is quite strange is that It works correctly (bold highlight) if I re-evaluate my init.el right after launching emacs. Here is my configuration. I will look into the the line your pointed at but I am asking in case there is any obvious mistakes

```
(use-package bespoke-themes
  :straight (:host github :repo "mclear-tools/bespoke-themes" :branch "main")
  :config
  ;; Set evil cursor colors
  ;; (setq bespoke-set-evil-cursors t)
  ;; Set use of italics
  (setq bespoke-set-italic-comments t
        bespoke-set-italic-keywords t)
  ;; Set variable pitch
  (setq bespoke-set-variable-pitch nil)
  ;; Set initial theme variant
  ;; (setq bespoke-set-theme 'light)
  ;; Load theme
  (load-theme 'bespoke t))

;; Make a clean & minimalist frame
(use-package frame
  :straight (:type built-in)
  :config
  (setq-default default-frame-alist
                (append (list
			 '(font . "Roboto Mono:style=regular:size=22") ;; NOTE: substitute whatever font you prefer here
                '(internal-border-width . 20)
                '(left-fringe    . 0)
                '(right-fringe   . 0)
                '(tool-bar-lines . 0)
                '(menu-bar-lines . 0)
                '(vertical-scroll-bars . nil))))
  (setq-default window-resize-pixelwise t)
  (setq-default frame-resize-pixelwise t)
  )

(use-package bespoke-modeline
  :straight (:type git :host github :repo "mclear-tools/bespoke-modeline") 
  :init
  ;; Set header line
  (setq bespoke-modeline-position 'top)
  ;; Set mode-line height
  (setq bespoke-modeline-size 3)
  ;; Show diff lines in mode-line
  (setq bespoke-modeline-git-diff-mode-line t)
  ;; Set mode-line cleaner
  (setq bespoke-modeline-cleaner t)
  ;; Use mode-line visual bell
  ;; (setq bespoke-modeline-visual-bell t)
  ;; Set vc symbol
  (setq  bespoke-modeline-vc-symbol "G:")
  :config
  (bespoke-modeline-mode))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "Roboto Mono" :foundry "outline" :slant normal :weight normal :height 110 :width normal)))))
```

**Comment by mclearc** [comment]
Your setup looks fine. I suspect this has something to do with the order in which you're loading helm and the theme. Assuming you use use-package for helm as well you might also try putting the following and see if this resolves the issue.

```emacs-lisp
(use-package helm
:after bespoke-themes
:custom-face (helm-selection ((t (:foreground bespoke-subtle :weight bold)))
:config
rest of helm config goes here...
```

**Comment by proudot** [comment]
That didn't work but it gave me the key to the solution!  I noticed that executing merely the block `(use-package bespoke-themes ... )`  after startup solved the highlighting problem. So the following codes works:
```
(use-package bespoke-themes
  :after helm
  :straight (:host github :repo "mclear-tools/bespoke-themes" :branch "main")
  :config
  (setq bespoke-set-italic-comments t
        bespoke-set-italic-keywords t)
  (setq bespoke-set-variable-pitch nil)
  (load-theme 'bespoke t)
)
```
