### ISSUE TITLE
Error (use-package): bespoke-themes/:config: Wrong type argument: stringp, bespoke-faded

### ISSUE THREAD

**Issue by jilen** [mclear-tools/bespoke-themes#4]
Cannot load manually with `use-package`
```lisp 
(use-package bespoke-themes
    :load-path "~/.emacs.d/themes/bespoke-themes"
    :init (add-to-list 'custom-theme-load-path "~/.emacs.d/themes/bespoke-themes")
    :config
    (setq bespoke-set-mode-line 'header)
    ;; Set mode line height
    (setq bespoke-set-mode-line-height 3)
    ;; Set evil cursor colors
    (setq bespoke-set-evil-cursors t)
    ;; Use mode line visual bell
    (setq bespoke-set-visual-bell t)
    ;; Set use of italics
    (setq bespoke-set-italic-comments t
          bespoke-set-italic-keywords t)
    ;; Set variable pitch
    (setq bespoke-set-variable-pitch t)
    ;; Set initial theme variant
    (setq bespoke-set-theme 'light)
    ;; Load theme
    (load-theme 'bespoke t))
```

It complains
```
Error (use-package): bespoke-themes/:config: Wrong type argument: stringp, bespoke-faded Disable showing Disable logging
```

**Comment by mclearc** [comment]
Hmm. It is a little hard for me to tell what the problem is. Have you tried it without both the `:load-path` and '`(add-to-list)` options?  I don't think you need both. If you're installing packages normally themes should be picked up in the load-path without doing any explicit statements.

**Comment by mclearc** [comment]
I haven't been able to reproduce this using the `use-package` setup you give above. And I also use `:load-path` for my setup and haven't had any issues. For what it's worth I use the below function for getting all custom themes from a set directory.

```emacs-lisp
;; set theme dir 
(setq-default custom-theme-directory (concat cpm-local-dir "custom-themes/"))
;; find all themes recursively in custom-theme-folder
(let ((basedir custom-theme-directory))
  (dolist (f (directory-files basedir))
    (if (and (not (or (equal f ".") (equal f "..")))
             (file-directory-p (concat basedir f)))
        (add-to-list 'custom-theme-load-path (concat basedir f)))))
```

**Comment by jilen** [comment]
If not add dir to load path , it complains
```
File is missing: Cannot open load file, No such file or directory, bespoke-modeline
```
And I am use `emacs-28` with native-comp

**Comment by mclearc** [comment]
just checking -- does the below work for you? This is basically the expansion of use-package macro.

```emacs-lisp
(eval-and-compile
  (add-to-list 'load-path "~/.emacs.d/.. path to bespoke-themes/"))
(eval-and-compile
  (add-to-list 'custom-theme-load-path "~/.emacs.d/.. path to bespoke-themes/"))
(require 'bespoke-themes nil t)

;; Set mode line as header line
(setq bespoke-set-mode-line 'header)
;; Set mode line height
(setq bespoke-set-mode-line-height 3)
;; Set up evil cursor colors
(setq bespoke-set-evil-cursors t)
;; Use mode line visual bell
(setq bespoke-set-visual-bell t)
;; Set use of italics
(setq bespoke-set-italic-comments t
      bespoke-set-italic-keywords t)
;; Set variable pitch
(setq bespoke-set-variable-pitch t)
;; Set initial theme variant
(setq bespoke-set-theme 'dark)
;; Load theme
(load-theme 'bespoke t)
```

**Comment by jilen** [comment]
No lucky still fail with
```
Debugger entered--Lisp error: (wrong-type-argument stringp bespoke-faded)
  set-face-attribute(ivy-yanked-word #<frame *scratch* 0x7fa9e3818230> :foreground bespoke-faded)
  face-spec-set-2(ivy-yanked-word #<frame *scratch* 0x7fa9e3818230> (:foreground bespoke-faded))
  face-spec-recalc(ivy-yanked-word #<frame *scratch* 0x7fa9e3818230>)
  custom-theme-recalc-face(ivy-yanked-word)
  enable-theme(bespoke)
```

**Comment by jilen** [comment]
@mclearc  I guess this may related to name conflicts,  there are both (defcustom bespoke-faded) and (defface bespoke-faded)

**Comment by florhizome** [comment]
I use 28 / native compile too and get major issues but it didn't work out before, too.
I will open a new issue for me for other things - when I directly declare with use-package (+ straight.el) I directly get an cl error. 

But when I get around this I too have the issue that seemingly only the main file will load, as i can only command "bespoke/toggle-themes" from the commandline. The autoloads from ...modeline.el  and theme.el are not available. 
I used to get around this with "require"-ing the modeline (which was my main interest), but even that doesn't work anymore now. 
I also had partially problems with the faded and strong faces when using the theme like this.

**Comment by florhizome** [comment]
I think one problem might just be the theme being defined in bespoke-theme.el but the declaration telling to search for it in bespoke-themes.el

**Comment by mclearc** [comment]
Unfortunately I'm still not able to reproduce this problem. The [above](https://github.com/mclear-tools/bespoke-themes/issues/4#issuecomment-862442254) settings work fine for me using `emacs -q -l test.el` (where `test.el` contains only the above code) from the command line (with emacs 28). 

My sense is that there are two things going on. First you need to make sure that `bespoke-modeline.el` is available on your load-path. Second,  if you're doing a manual load of the theme you need to be sure that `bespoke-themes` is available on your custom-theme-load-path. 

If you can get it working with the [above configuration](https://github.com/mclear-tools/bespoke-themes/issues/4#issuecomment-862442254) then you should be able to use your use-package with the load-path declared manually *so long as you have the custom-theme-load-path` properly. Here's the relevant information from the [emacs manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Custom-Themes.html)

> Type M-x customize-themes to switch to a buffer named *Custom Themes*, which lists the Custom themes that Emacs knows about. By default, Emacs looks for theme files in two locations: the directory specified by the variable custom-theme-directory (which defaults to ~/.emacs.d/), and a directory named etc/themes in your Emacs installation (see the variable data-directory). The latter contains several Custom themes distributed with Emacs that customize Emacs’s faces to fit various color schemes. (Note, however, that Custom themes need not be restricted to this purpose; they can be used to customize variables too.)

> If you want Emacs to look for Custom themes in some other directory, add the directory to the list variable custom-theme-load-path. Its default value is (custom-theme-directory t); here, the symbol custom-theme-directory has the special meaning of the value of the variable custom-theme-directory, while t stands for the built-in theme directory etc/themes. The themes listed in the *Custom Themes* buffer are those found in the directories specified by custom-theme-load-path.

**Comment by jilen** [comment]
Confirmed, this is related to `ivy-xref` or `all-the-icons-ivy` remove those just get things fixed

**Comment by florhizome** [comment]
ah ok, but other themes don't have those problems, also compromising on other packages isn't really a solution. 
(Maybe changing the load-order with use-package is a figurable workaround, I guess I'll try around...)
Sorry if i'm a bit annoying here, @mclearc can close this anytime he wants...

**Comment by mclearc** [comment]
@florhizome the details of loading for the package are completely standard. If you load your theme for a non-standard place then you have to make sure that place is either "the directory specified by the variable custom-theme-directory (which defaults to ~/.emacs.d/), and a directory named etc/themes in your Emacs installation (see the variable data-directory)" as the manual says. And Ivy/counsel/swiper should work -- there was a typo in the declaration of faces but that has now been fixed.
