### ISSUE TITLE
Saving bandwidth by compressing screenshots or using SVG screenshots

### ISSUE THREAD

**Issue by akirak** [mclear-tools/bespoke-themes#8]
Hello, I tried to fix some issues in the code while I was trying out this theme.

This repository is relatively large (~ several mega bytes) because of screenshots in the repository. I'd recommend compressing the images using optipng or taking SVG screenshots instead.

By compressing the entire screenshots directory using optipng (`-o5`), you can reduce the size from 5.4M to 3.3M:

```
optipng -o5 dark-agenda.png
```

It is also possible to take SVG screenshots using `x-export-frames` function (see [this reddit thread](https://www.reddit.com/r/emacs/comments/idz35e/emacs_27_can_take_svg_screenshots_of_itself/)).

Even if you replace the images with a compressed version, the older version will still remain in the history, so it won't save bandwidth of normal clones (and actually increases the entire repository size). However, shallow clones (`--depth=1`) and partial clones (`--filter=blob:none`) will take advantage of the change, which will be important once you publish these themes to MELPA or somewhere. I hope you will consider it.

**Comment by mclearc** [comment]
Thanks -- I hadn't been thinking about space issues. I've been meaning to tidy up for Melpa but haven't had the time.
